name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Setup Python
        with:
          python-version: '3.8.10'
      - uses: actions/checkout@v2
      - name: Run django unit tests
        run:
          pip3 install  django
          python3 manage.py test
